# Generated by Django 3.0.6 on 2020-06-02 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
