# Generated by Django 3.0.6 on 2020-06-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi', '0003_auto_20200602_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsusers',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
